services:
  app:
    build: .
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app # Синхронизира локалните файлове с контейнера
    ports:
      - "5001:5001"
    environment:
      MONGODB_URI: mongodb+srv://ppchuchkov1:5NYj8SQ3zaqK5qjd@cluster0.5ifkd.mongodb.net/NodeCourse?retryWrites=true&w=majority&appName=Cluster0
      STRIPE_SECRET_KEY: sk_test_51Hkv2kGETpcP6ndNX7BE2xIyofmsBUGXK2yFyxI7S7FOnfABvGbCzKnoif39gJHBlb9NixcbcmurVimVJ3KoorFG00SoLPy2w6
      STRIPE_WEBHOOK_SECRET: whsec_WIH6SMnq2Lx7R1wqo8wwMXCWU7Iywx5F
      GMAIL_USER: ppchuchkov1@gmail.com
      BREVO_APP_PASSWORD: jO7PU0ZC6SvkEsc4
    command: ["node", "src/app.js"] # Използвайте node вместо nodemon

  mongo:
    image: mongo:7.0
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
