name: Deploy Docker

on:
  push:
    branches:
      - main # Заменете с основния клон на вашето репозиторий (например, master)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build . -t your-dockerhub-username/your-image-name:latest

      - name: Push Docker image
        run: docker push your-dockerhub-username/your-image-name:latest

      - name: Deploy to Docker
        run: |
          ssh username@your-server-ip << 'EOF'
          docker pull your-dockerhub-username/your-image-name:latest
          docker stop your-container-name || true
          docker rm your-container-name || true
          docker run -d --name your-container-name -p 5001:5001 your-dockerhub-username/your-image-name:latest
          EOF
